# Use the official MySQL Docker image
FROM mysql:latest

# Set the MySQL root password (replace with your desired password)
ENV MYSQL_ROOT_PASSWORD=password

# Set a non-root user and password (replace with your desired username and password)
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=user

# (Optional) Create a new database (replace with your desired database name)
ENV MYSQL_DATABASE=courier_db

# Expose the MySQL port
EXPOSE 3306